function build_PipeSAR24_model(mdl)
% build_PipeSAR24_model  程序化生成 24-bit 三级 Pipelined-SAR ADC 的 Simulink 模型
%
% 用法：
%   PipeSAR_params;             % 先加载参数（必须）
%   build_PipeSAR24_model;      % 生成并保存 PipeSAR24.slx
%
% 模型结构（每个仿真步 = 一个 ADC 采样周期，完成一次完整流水线转换）：
%   [Vin_p/Vin_n] -> SAR_Stage1(8b,冗余) -> RA1 -> SAR_Stage2(8b,冗余)
%                 -> RA2 -> SAR_Stage3(10b) -> Digital_Backend(数字校准接口)
%
% 数字接口（你的校准算法接入点）：
%   1) 在线方式：替换子系统 PipeSAR24/Digital_Backend/Digital_Calibration
%      内的 MATLAB 代码（输入 D1[1x8], D2[1x8], D3[1x10]，输出 Dout, Vout），
%      或直接在 workspace 中修改权重 W1/W2/W3/OFS。
%   2) 离线方式：模型已通过 To Workspace 输出原始码 sim_D1/sim_D2/sim_D3，
%      可在 MATLAB 中用你的算法离线重组（见 My_Digital_Calibration.m）。
%
% 依赖：base workspace 中已运行 PipeSAR_params.m。

if nargin < 1, mdl = 'PipeSAR24'; end

% 检查参数是否已加载
if ~evalin('base','exist(''N1'',''var'')')
    evalin('base','PipeSAR_params');
end
N1 = evalin('base','N1'); N2 = evalin('base','N2'); N3 = evalin('base','N3');

%% 新建模型
if bdIsLoaded(mdl), close_system(mdl,0); end
if exist([mdl '.slx'],'file'), delete([mdl '.slx']); end
new_system(mdl);
open_system(mdl);

set_param(mdl, ...
    'SolverType','Fixed-step', ...
    'Solver','FixedStepDiscrete', ...
    'FixedStep','1/fs', ...
    'StopTime','(num-1)/fs', ...
    'SaveTime','off');

%% ------------------- 信号源 -------------------
% 注意：必须开启插值（Interpolate on）。若关闭插值，From Workspace 要求
% 仿真步进时刻与 timeseries 时间戳逐位相等，浮点舍入差 1 ulp 就会输出
% 滞后一拍的旧值，等效引入整周期抖动，性能崩塌且与 fs 取值有关。
% 开启插值后 1 ulp 时间偏差带来的幅度误差仅 ~1e-12 V，远低于 24-bit LSB。
add_block('simulink/Sources/From Workspace',[mdl '/Vinp_src'], ...
    'VariableName','Vinp_ts','SampleTime','1/fs','Interpolate','on', ...
    'OutputAfterFinalValue','Holding final value', ...
    'Position',[40 80 130 110]);
add_block('simulink/Sources/From Workspace',[mdl '/Vinn_src'], ...
    'VariableName','Vinn_ts','SampleTime','1/fs','Interpolate','on', ...
    'OutputAfterFinalValue','Holding final value', ...
    'Position',[40 160 130 190]);

%% ------------------- 第一级 SAR（带冗余, SAR_FUN_R 行为）-------------------
add_block('simulink/User-Defined Functions/MATLAB Function',[mdl '/SAR_Stage1'], ...
    'Position',[210 70 330 200]);
setMFB([mdl '/SAR_Stage1'], sarScriptR(1, N1), ...
    {'Vref1','C_act_p1','C_act_n1','C_tot_p1','C_tot_n1', ...
     'Vn_sig_p1','Vn_sig_n1','Comp_offset1','Comp_noise'});

%% ------------------- 级间放大器 1（RA_FUN 行为）-------------------
add_block('simulink/User-Defined Functions/MATLAB Function',[mdl '/RA1'], ...
    'Position',[410 110 510 200]);
setMFB([mdl '/RA1'], raScript(1), ...
    {'Av','GBW','Cs1','Ch1','Vcm','Amp_offset','Amp_noise','fs'});

%% ------------------- 第二级 SAR（带冗余）-------------------
add_block('simulink/User-Defined Functions/MATLAB Function',[mdl '/SAR_Stage2'], ...
    'Position',[590 70 710 200]);
setMFB([mdl '/SAR_Stage2'], sarScriptR(2, N2), ...
    {'Vref2','C_act_p2','C_act_n2','C_tot_p2','C_tot_n2', ...
     'Vn_sig_p2','Vn_sig_n2','Comp_offset2','Comp_noise'});

%% ------------------- 级间放大器 2 -------------------
add_block('simulink/User-Defined Functions/MATLAB Function',[mdl '/RA2'], ...
    'Position',[790 110 890 200]);
setMFB([mdl '/RA2'], raScript(2), ...
    {'Av','GBW','Cs2','Ch2','Vcm','Amp_offset','Amp_noise','fs'});

%% ------------------- 第三级 SAR（SAR_FUN 行为，末位仅比较）-------------------
add_block('simulink/User-Defined Functions/MATLAB Function',[mdl '/SAR_Stage3'], ...
    'Position',[970 70 1090 200]);
setMFB([mdl '/SAR_Stage3'], sarScriptLast(3, N3), ...
    {'Vref3','C_act_p3','C_act_n3','C_tot_p3','C_tot_n3', ...
     'Vn_sig_p3','Vn_sig_n3','Comp_offset3','Comp_noise'});

%% ------------------- 数字后端子系统（校准算法接口）-------------------
bk = [mdl '/Digital_Backend'];
add_block('built-in/Subsystem', bk, 'Position',[1170 260 1330 380]);

add_block('built-in/Inport', [bk '/D1'], 'Port','1','Position',[40 40 70 56]);
add_block('built-in/Inport', [bk '/D2'], 'Port','2','Position',[40 100 70 116]);
add_block('built-in/Inport', [bk '/D3'], 'Port','3','Position',[40 160 70 176]);

add_block('simulink/User-Defined Functions/MATLAB Function',[bk '/Digital_Calibration'], ...
    'Position',[150 60 300 160]);
setMFB([bk '/Digital_Calibration'], calScript(), {'W1','W2','W3','OFS','Kv'});

add_block('built-in/Outport',[bk '/Dout'],'Port','1','Position',[380 70 410 86]);
add_block('built-in/Outport',[bk '/Vout'],'Port','2','Position',[380 130 410 146]);

add_line(bk,'D1/1','Digital_Calibration/1','autorouting','on');
add_line(bk,'D2/1','Digital_Calibration/2','autorouting','on');
add_line(bk,'D3/1','Digital_Calibration/3','autorouting','on');
add_line(bk,'Digital_Calibration/1','Dout/1','autorouting','on');
add_line(bk,'Digital_Calibration/2','Vout/1','autorouting','on');

%% ------------------- 数据记录（To Workspace）-------------------
twPos = @(x,y) [x y x+110 y+30];
add_block('simulink/Sinks/To Workspace',[mdl '/log_D1'], ...
    'VariableName','sim_D1','SaveFormat','Array','MaxDataPoints','inf', ...
    'Position',twPos(410,300));
add_block('simulink/Sinks/To Workspace',[mdl '/log_D2'], ...
    'VariableName','sim_D2','SaveFormat','Array','MaxDataPoints','inf', ...
    'Position',twPos(790,300));
add_block('simulink/Sinks/To Workspace',[mdl '/log_D3'], ...
    'VariableName','sim_D3','SaveFormat','Array','MaxDataPoints','inf', ...
    'Position',twPos(1170,80));
add_block('simulink/Sinks/To Workspace',[mdl '/log_Dout'], ...
    'VariableName','sim_Dout','SaveFormat','Array','MaxDataPoints','inf', ...
    'Position',twPos(1420,270));
add_block('simulink/Sinks/To Workspace',[mdl '/log_Vout'], ...
    'VariableName','sim_Vout','SaveFormat','Array','MaxDataPoints','inf', ...
    'Position',twPos(1420,340));
% 记录各级模拟余差（便于基于余差的校准/调试）
add_block('simulink/Sinks/To Workspace',[mdl '/log_Vres1p'], ...
    'VariableName','sim_Vres1p','SaveFormat','Array','MaxDataPoints','inf', ...
    'Position',twPos(410,360));
add_block('simulink/Sinks/To Workspace',[mdl '/log_Vres1n'], ...
    'VariableName','sim_Vres1n','SaveFormat','Array','MaxDataPoints','inf', ...
    'Position',twPos(410,420));

%% ------------------- 连线 -------------------
add_line(mdl,'Vinp_src/1','SAR_Stage1/1','autorouting','on');
add_line(mdl,'Vinn_src/1','SAR_Stage1/2','autorouting','on');

% Stage1: out1=D1, out2=Vresp1, out3=Vresn1
add_line(mdl,'SAR_Stage1/1','Digital_Backend/1','autorouting','on');
add_line(mdl,'SAR_Stage1/1','log_D1/1','autorouting','on');
add_line(mdl,'SAR_Stage1/2','RA1/1','autorouting','on');
add_line(mdl,'SAR_Stage1/3','RA1/2','autorouting','on');
add_line(mdl,'SAR_Stage1/2','log_Vres1p/1','autorouting','on');
add_line(mdl,'SAR_Stage1/3','log_Vres1n/1','autorouting','on');

add_line(mdl,'RA1/1','SAR_Stage2/1','autorouting','on');
add_line(mdl,'RA1/2','SAR_Stage2/2','autorouting','on');

add_line(mdl,'SAR_Stage2/1','Digital_Backend/2','autorouting','on');
add_line(mdl,'SAR_Stage2/1','log_D2/1','autorouting','on');
add_line(mdl,'SAR_Stage2/2','RA2/1','autorouting','on');
add_line(mdl,'SAR_Stage2/3','RA2/2','autorouting','on');

add_line(mdl,'RA2/1','SAR_Stage3/1','autorouting','on');
add_line(mdl,'RA2/2','SAR_Stage3/2','autorouting','on');

add_line(mdl,'SAR_Stage3/1','Digital_Backend/3','autorouting','on');
add_line(mdl,'SAR_Stage3/1','log_D3/1','autorouting','on');

add_line(mdl,'Digital_Backend/1','log_Dout/1','autorouting','on');
add_line(mdl,'Digital_Backend/2','log_Vout/1','autorouting','on');

%% 保存
save_system(mdl);
fprintf('模型 %s.slx 已生成并保存。\n', mdl);
end

%% ======================================================================
%%                          本地辅助函数
%% ======================================================================

function setMFB(blockPath, script, paramNames)
% 写入 MATLAB Function 块代码，并把指定输入参数的作用域改为 Parameter
% （Parameter 作用域的数据会自动从 base workspace 解析同名变量）
rt = sfroot;
ch = rt.find('-isa','Stateflow.EMChart','Path',blockPath);
if isempty(ch)
    error('找不到 MATLAB Function 块: %s', blockPath);
end
ch = ch(1);
ch.Script = script;
for kk = 1:numel(paramNames)
    d = ch.find('-isa','Stateflow.Data','Name',paramNames{kk});
    if isempty(d)
        error('块 %s 中找不到数据 %s', blockPath, paramNames{kk});
    end
    d(1).Scope = 'Parameter';
end
end

function s = sarScriptR(stg, Nb)
% 生成带冗余的 SAR 级代码（对应 SAR_FUN_R：N 位全部开关，余差含末位反馈）
% 每个仿真步对当前采样值完成一次完整 N 位 SAR 转换（行为级，Vcm-Based 时序）
s = sprintf([ ...
'function [D%d, Vresp%d, Vresn%d] = fcn(Vip0, Vin0, Vref%d, C_act_p%d, C_act_n%d, C_tot_p%d, C_tot_n%d, Vn_sig_p%d, Vn_sig_n%d, Comp_offset%d, Comp_noise)\n' ...
'%%#codegen\n' ...
'%% 第 %d 级 SAR（%d bit，带冗余，移植自 SAR_FUN_R，Vcm-Based 时序）\n' ...
'Vip = Vip0 + Vn_sig_p%d*randn;   %% kT/C 采样噪声\n' ...
'Vin = Vin0 + Vn_sig_n%d*randn;\n' ...
'D%d = zeros(1,%d);\n' ...
'for i = 1:%d\n' ...
'    if Vip - Vin <= Comp_offset%d + Comp_noise*randn\n' ...
'        D%d(i) = 0;\n' ...
'        Vip = Vip + Vref%d/2*C_act_p%d(i)/C_tot_p%d;\n' ...
'        Vin = Vin - Vref%d/2*C_act_n%d(i)/C_tot_n%d;\n' ...
'    else\n' ...
'        D%d(i) = 1;\n' ...
'        Vip = Vip - Vref%d/2*C_act_p%d(i)/C_tot_p%d;\n' ...
'        Vin = Vin + Vref%d/2*C_act_n%d(i)/C_tot_n%d;\n' ...
'    end\n' ...
'end\n' ...
'Vresp%d = Vip;   %% 转换完成后的余差电压（送级间放大器）\n' ...
'Vresn%d = Vin;\n'], ...
stg,stg,stg, stg,stg,stg,stg,stg,stg,stg,stg, ...
stg,Nb, stg,stg, stg,Nb, Nb, stg, ...
stg, stg,stg,stg, stg,stg,stg, ...
stg, stg,stg,stg, stg,stg,stg, ...
stg,stg);
end

function s = sarScriptLast(stg, Nb)
% 生成末级 SAR 代码（对应 SAR_FUN：前 N-1 位开关，最后一位仅比较）
s = sprintf([ ...
'function D%d = fcn(Vip0, Vin0, Vref%d, C_act_p%d, C_act_n%d, C_tot_p%d, C_tot_n%d, Vn_sig_p%d, Vn_sig_n%d, Comp_offset%d, Comp_noise)\n' ...
'%%#codegen\n' ...
'%% 第 %d 级 SAR（%d bit，末级，移植自 SAR_FUN，最后一位不开关）\n' ...
'Vip = Vip0 + Vn_sig_p%d*randn;\n' ...
'Vin = Vin0 + Vn_sig_n%d*randn;\n' ...
'D%d = zeros(1,%d);\n' ...
'for i = 1:%d\n' ...
'    if Vip - Vin <= Comp_offset%d + Comp_noise*randn\n' ...
'        D%d(i) = 0;\n' ...
'        Vip = Vip + Vref%d/2*C_act_p%d(i)/C_tot_p%d;\n' ...
'        Vin = Vin - Vref%d/2*C_act_n%d(i)/C_tot_n%d;\n' ...
'    else\n' ...
'        D%d(i) = 1;\n' ...
'        Vip = Vip - Vref%d/2*C_act_p%d(i)/C_tot_p%d;\n' ...
'        Vin = Vin + Vref%d/2*C_act_n%d(i)/C_tot_n%d;\n' ...
'    end\n' ...
'end\n' ...
'if Vip - Vin <= Comp_offset%d + Comp_noise*randn\n' ...
'    D%d(%d) = 0;\n' ...
'else\n' ...
'    D%d(%d) = 1;\n' ...
'end\n'], ...
stg,stg,stg,stg,stg,stg,stg,stg,stg, ...
stg,Nb, stg,stg, stg,Nb, Nb-1, stg, ...
stg, stg,stg,stg, stg,stg,stg, ...
stg, stg,stg,stg, stg,stg,stg, ...
stg, stg,Nb, stg,Nb);
end

function s = raScript(stg)
% 生成级间余差放大器代码（移植自 RA_FUN，含有限增益/有限带宽/失调/噪声）
s = sprintf([ ...
'function [Voutp%d, Voutn%d] = fcn(Vip, Vin, Av, GBW, Cs%d, Ch%d, Vcm, Amp_offset, Amp_noise, fs)\n' ...
'%%#codegen\n' ...
'%% 第 %d 个级间余差放大器（移植自 RA_FUN）\n' ...
'Av_abs = 10^(Av/20);                %% 开环增益绝对值\n' ...
'beta   = Cs%d/Ch%d;                  %% 反馈系数，闭环增益约 1/beta\n' ...
'tamp   = 0.4/fs;                    %% 放大建立时间\n' ...
'toi    = 1/(2*pi*beta*GBW);         %% 闭环时间常数\n' ...
'g = (Av_abs/(1+beta*Av_abs))*(1-exp(-tamp/toi));  %% 含静态+动态误差的实际增益\n' ...
'Voutp%d = Vcm + g*(Vip - Vcm + Amp_offset + Amp_noise*randn);\n' ...
'Voutn%d = Vcm + g*(Vin - Vcm);\n'], ...
stg,stg,stg,stg, stg, stg,stg, stg,stg);
end

function s = calScript()
% 数字后端默认代码：理想权重重组（= 原脚本的 DOUT1+DOUT2+DOUT3-OFS）
% ====== 这里就是预留给你的数字校准算法的接口 ======
s = sprintf([ ...
'function [Dout, Vout] = fcn(D1, D2, D3, W1, W2, W3, OFS, Kv)\n' ...
'%%#codegen\n' ...
'%% ================= 数字校准接口 =================\n' ...
'%% 输入:  D1 [1xN1]  第一级原始码 (MSB first)\n' ...
'%%        D2 [1xN2]  第二级原始码\n' ...
'%%        D3 [1xN3]  第三级原始码\n' ...
'%% 参数:  W1/W2/W3   各级位权 (默认理想二进制权重, 可由校准算法更新)\n' ...
'%%        OFS        失调修正项, Kv = Vref1/2^N\n' ...
'%% 输出:  Dout 校准后的数字码, Vout 折算电压\n' ...
'%%\n' ...
'%% >>> 在此处替换/插入你的数字校准算法 <<<\n' ...
'%% 默认实现: 理想重组 (与 PipeSAR_test_3stage.m 一致)\n' ...
'Dout = D1*W1(:) + D2*W2(:) + D3*W3(:) - OFS;\n' ...
'Vout = Dout*Kv;\n']);
end
